### ISSUE TITLE
Incorrect ending quote 

### ISSUE THREAD

**Issue by thomasdbock** [kellym/smartquotesjs#18]
We found out an incorrect ending quote in one of our test sites.
When we use multiple non-whitespace characters before and after the quote, it will consider an ending quote as a starter quote.

Examples can be found [here](https://regex101.com/r/7V8HZH/3)

These scenario's result in these:
![image](https://cloud.githubusercontent.com/assets/1466381/23787759/ccec49e6-0573-11e7-9bd9-8b97eebad192.png)

![image](https://cloud.githubusercontent.com/assets/1466381/23787797/03a23a2c-0574-11e7-9e7e-a212a5998098.png)

![image](https://cloud.githubusercontent.com/assets/1466381/23787954/be6d0008-0574-11e7-8c16-af9865dda12f.png)

**Comment by kellym** [comment]
@thomasdbock sorry for the delay in resolving this. I just pushed up a new version to npm, version 2.0.1, that should take care of this.  There's a new test for this scenario as well.

Thanks for reporting this, and let me know if you run into anything else!

**Comment by thomasdbock** [comment]
After installing 2.0.1 and doing a quick run, it seems like this isn't fixed yet?
![image](https://cloud.githubusercontent.com/assets/1466381/26539547/51a170d6-444d-11e7-8774-1222d18f47db.png)

**Comment by kellym** [comment]
Did some tests and apparently I fixed it for a single word but not for multiple. Working on a fix.

**Comment by kellym** [comment]
Should be resolved in 2.0.2.
